// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateSourceDir() {
  return window['go']['main']['App']['CreateSourceDir']();
}

export function GetPreferences() {
  return window['go']['main']['App']['GetPreferences']();
}

export function ListAllTracks() {
  return window['go']['main']['App']['ListAllTracks']();
}

export function ListFavTracks() {
  return window['go']['main']['App']['ListFavTracks']();
}

export function ReloadAppResources() {
  return window['go']['main']['App']['ReloadAppResources']();
}

export function UpdatePreferences(arg1) {
  return window['go']['main']['App']['UpdatePreferences'](arg1);
}
