// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {sqlcDb} from '../models';

export function CreateSourceDir():Promise<void>;

export function GetPreferences():Promise<config.Preferences>;

export function ListAllTracks():Promise<Array<sqlcDb.Track>>;

export function ListFavTracks():Promise<Array<sqlcDb.Track>>;

export function PauseResume():Promise<void>;

export function PlayTrack(arg1:sqlcDb.Track):Promise<void>;

export function ReloadAppResources():Promise<void>;

export function StarTrack(arg1:sqlcDb.Track):Promise<void>;

export function UpdatePreferences(arg1:config.Preferences):Promise<void>;
