// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';

export function Greet(arg1:number):Promise<string>;

export function InitAppResources():Promise<void>;

export function LoadConfig():Promise<config.Preferences>;

export function Testt(arg1:number):Promise<string>;
