// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddToQueue(arg1) {
  return window['go']['main']['App']['AddToQueue'](arg1);
}

export function CreateSourceDir() {
  return window['go']['main']['App']['CreateSourceDir']();
}

export function GetCurrent() {
  return window['go']['main']['App']['GetCurrent']();
}

export function GetPreferences() {
  return window['go']['main']['App']['GetPreferences']();
}

export function ListAllTracks() {
  return window['go']['main']['App']['ListAllTracks']();
}

export function ListFavTracks() {
  return window['go']['main']['App']['ListFavTracks']();
}

export function ListQueue() {
  return window['go']['main']['App']['ListQueue']();
}

export function PauseResume() {
  return window['go']['main']['App']['PauseResume']();
}

export function PlayTrack(arg1) {
  return window['go']['main']['App']['PlayTrack'](arg1);
}

export function ReloadAppResources() {
  return window['go']['main']['App']['ReloadAppResources']();
}

export function StarTrack(arg1) {
  return window['go']['main']['App']['StarTrack'](arg1);
}

export function UpdatePreferences(arg1) {
  return window['go']['main']['App']['UpdatePreferences'](arg1);
}
