// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: albums.sql

package sqlcDb

import (
	"context"
	"database/sql"
)

const createFavAlbum = `-- name: CreateFavAlbum :exec
INSERT INTO favouriteAlbums (id, created_at, starred, album_name)
VALUES (?1, ?2, ?3, ?4)
`

type CreateFavAlbumParams struct {
	ID        string        `json:"id"`
	CreatedAt int64         `json:"created_at"`
	Starred   sql.NullInt64 `json:"starred"`
	AlbumName string        `json:"album_name"`
}

func (q *Queries) CreateFavAlbum(ctx context.Context, arg CreateFavAlbumParams) error {
	_, err := q.db.ExecContext(ctx, createFavAlbum,
		arg.ID,
		arg.CreatedAt,
		arg.Starred,
		arg.AlbumName,
	)
	return err
}

const listDistinctAlbums = `-- name: ListDistinctAlbums :many
SELECT DISTINCT album FROM tracks ORDER BY title
`

func (q *Queries) ListDistinctAlbums(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listDistinctAlbums)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var album string
		if err := rows.Scan(&album); err != nil {
			return nil, err
		}
		items = append(items, album)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFavAlbums = `-- name: ListFavAlbums :many
SELECT id, created_at, starred, album_name FROM favouriteAlbums ORDER BY album_name
`

func (q *Queries) ListFavAlbums(ctx context.Context) ([]Favouritealbum, error) {
	rows, err := q.db.QueryContext(ctx, listFavAlbums)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Favouritealbum
	for rows.Next() {
		var i Favouritealbum
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Starred,
			&i.AlbumName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFavAlbum = `-- name: UpdateFavAlbum :exec
UPDATE favouriteAlbums SET starred = ?1 WHERE album_name = ?2
`

type UpdateFavAlbumParams struct {
	Starred   sql.NullInt64 `json:"starred"`
	AlbumName string        `json:"album_name"`
}

func (q *Queries) UpdateFavAlbum(ctx context.Context, arg UpdateFavAlbumParams) error {
	_, err := q.db.ExecContext(ctx, updateFavAlbum, arg.Starred, arg.AlbumName)
	return err
}
