// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: artists.sql

package sqlcDb

import (
	"context"
	"database/sql"
)

const createFavArtist = `-- name: CreateFavArtist :exec
INSERT INTO favouriteArtists
(id, created_at, starred, artist)
VALUES (?1, ?2, ?3, ?4)
`

type CreateFavArtistParams struct {
	ID        string        `json:"id"`
	CreatedAt int64         `json:"created_at"`
	Starred   sql.NullInt64 `json:"starred"`
	Artist    string        `json:"artist"`
}

func (q *Queries) CreateFavArtist(ctx context.Context, arg CreateFavArtistParams) error {
	_, err := q.db.ExecContext(ctx, createFavArtist,
		arg.ID,
		arg.CreatedAt,
		arg.Starred,
		arg.Artist,
	)
	return err
}

const listFavArtists = `-- name: ListFavArtists :many
SELECT id, created_at, starred, artist FROM favouriteArtists ORDER BY artist
`

func (q *Queries) ListFavArtists(ctx context.Context) ([]Favouriteartist, error) {
	rows, err := q.db.QueryContext(ctx, listFavArtists)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Favouriteartist
	for rows.Next() {
		var i Favouriteartist
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Starred,
			&i.Artist,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
