// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcDb

import (
	"database/sql"
)

type Favouritealbum struct {
	ID        string        `json:"id"`
	CreatedAt int64         `json:"created_at"`
	Starred   sql.NullInt64 `json:"starred"`
	AlbumName string        `json:"album_name"`
}

type Favouriteartist struct {
	ID        string        `json:"id"`
	CreatedAt int64         `json:"created_at"`
	Starred   sql.NullInt64 `json:"starred"`
	Artist    string        `json:"artist"`
}

type Playlist struct {
	ID        string         `json:"id"`
	CreatedAt int64          `json:"created_at"`
	Name      string         `json:"name"`
	CoverPath sql.NullString `json:"cover_path"`
	Starred   sql.NullInt64  `json:"starred"`
}

type Track struct {
	ID              string         `json:"id"`
	CreatedAt       int64          `json:"created_at"`
	Path            string         `json:"path"`
	Title           string         `json:"title"`
	Artist          string         `json:"artist"`
	Album           string         `json:"album"`
	Genre           sql.NullString `json:"genre"`
	Year            sql.NullInt64  `json:"year"`
	DurationSeconds sql.NullInt64  `json:"duration_seconds"`
	Starred         sql.NullInt64  `json:"starred"`
	IsMissing       sql.NullBool   `json:"is_missing"`
}

type TracksFt struct {
	ID     string `json:"id"`
	Title  string `json:"title"`
	Artist string `json:"artist"`
	Album  string `json:"album"`
}

type TracksToPlaylist struct {
	ID         string `json:"id"`
	CreatedAt  int64  `json:"created_at"`
	TrackID    string `json:"track_id"`
	PlaylistID string `json:"playlist_id"`
}
