// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: playlists.sql

package sqlcDb

import (
	"context"
	"database/sql"
)

const createPlaylist = `-- name: CreatePlaylist :exec
INSERT INTO playlists (
  id,
  createdAt,
  name,
  coverPath,
  starred
) VALUES (
  ?1,
  ?2,
  ?3,
  ?4,
  ?5
)
`

type CreatePlaylistParams struct {
	ID        string         `json:"id"`
	Createdat int64          `json:"createdat"`
	Name      string         `json:"name"`
	Coverpath sql.NullString `json:"coverpath"`
	Starred   sql.NullInt64  `json:"starred"`
}

func (q *Queries) CreatePlaylist(ctx context.Context, arg CreatePlaylistParams) error {
	_, err := q.db.ExecContext(ctx, createPlaylist,
		arg.ID,
		arg.Createdat,
		arg.Name,
		arg.Coverpath,
		arg.Starred,
	)
	return err
}

const deletePlaylist = `-- name: DeletePlaylist :exec
DELETE FROM playlists WHERE id = ?1
`

func (q *Queries) DeletePlaylist(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deletePlaylist, id)
	return err
}

const editPlaylist = `-- name: EditPlaylist :exec
UPDATE playlists SET
    name = ?1,
    coverPath = ?2,
    starred = ?3
WHERE id = ?4
`

type EditPlaylistParams struct {
	Name      string         `json:"name"`
	Coverpath sql.NullString `json:"coverpath"`
	Starred   sql.NullInt64  `json:"starred"`
	ID        string         `json:"id"`
}

func (q *Queries) EditPlaylist(ctx context.Context, arg EditPlaylistParams) error {
	_, err := q.db.ExecContext(ctx, editPlaylist,
		arg.Name,
		arg.Coverpath,
		arg.Starred,
		arg.ID,
	)
	return err
}

const getPlaylist = `-- name: GetPlaylist :one
SELECT id, createdat, name, coverpath, starred FROM playlists WHERE id = ?1
`

func (q *Queries) GetPlaylist(ctx context.Context, id string) (Playlist, error) {
	row := q.db.QueryRowContext(ctx, getPlaylist, id)
	var i Playlist
	err := row.Scan(
		&i.ID,
		&i.Createdat,
		&i.Name,
		&i.Coverpath,
		&i.Starred,
	)
	return i, err
}

const listFavPlaylists = `-- name: ListFavPlaylists :many
SELECT id, createdat, name, coverpath, starred FROM playlists WHERE starred IS NOT NULL ORDER BY name
`

func (q *Queries) ListFavPlaylists(ctx context.Context) ([]Playlist, error) {
	rows, err := q.db.QueryContext(ctx, listFavPlaylists)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Playlist
	for rows.Next() {
		var i Playlist
		if err := rows.Scan(
			&i.ID,
			&i.Createdat,
			&i.Name,
			&i.Coverpath,
			&i.Starred,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlaylists = `-- name: ListPlaylists :many
SELECT id, createdat, name, coverpath, starred FROM playlists ORDER BY name
`

func (q *Queries) ListPlaylists(ctx context.Context) ([]Playlist, error) {
	rows, err := q.db.QueryContext(ctx, listPlaylists)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Playlist
	for rows.Next() {
		var i Playlist
		if err := rows.Scan(
			&i.ID,
			&i.Createdat,
			&i.Name,
			&i.Coverpath,
			&i.Starred,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
