/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as SettingsRouteRouteImport } from "./routes/settings/route"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as ArtistsIndexRouteImport } from "./routes/artists/index"
import { Route as AlbumsIndexRouteImport } from "./routes/albums/index"
import { Route as TracksAllRouteRouteImport } from "./routes/tracks/all/route"
import { Route as PlaylistAllRouteRouteImport } from "./routes/playlist/all/route"
import { Route as PlaylistPlaylistIdRouteRouteImport } from "./routes/playlist/$playlistId/route"
import { Route as ArtistsArtistRouteRouteImport } from "./routes/artists/$artist/route"
import { Route as AlbumsAlbumNameRouteRouteImport } from "./routes/albums/$albumName/route"

const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsIndexRoute = ArtistsIndexRouteImport.update({
  id: "/artists/",
  path: "/artists/",
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumsIndexRoute = AlbumsIndexRouteImport.update({
  id: "/albums/",
  path: "/albums/",
  getParentRoute: () => rootRouteImport,
} as any)
const TracksAllRouteRoute = TracksAllRouteRouteImport.update({
  id: "/tracks/all",
  path: "/tracks/all",
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistAllRouteRoute = PlaylistAllRouteRouteImport.update({
  id: "/playlist/all",
  path: "/playlist/all",
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistPlaylistIdRouteRoute = PlaylistPlaylistIdRouteRouteImport.update({
  id: "/playlist/$playlistId",
  path: "/playlist/$playlistId",
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsArtistRouteRoute = ArtistsArtistRouteRouteImport.update({
  id: "/artists/$artist",
  path: "/artists/$artist",
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumsAlbumNameRouteRoute = AlbumsAlbumNameRouteRouteImport.update({
  id: "/albums/$albumName",
  path: "/albums/$albumName",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/settings": typeof SettingsRouteRoute
  "/albums/$albumName": typeof AlbumsAlbumNameRouteRoute
  "/artists/$artist": typeof ArtistsArtistRouteRoute
  "/playlist/$playlistId": typeof PlaylistPlaylistIdRouteRoute
  "/playlist/all": typeof PlaylistAllRouteRoute
  "/tracks/all": typeof TracksAllRouteRoute
  "/albums": typeof AlbumsIndexRoute
  "/artists": typeof ArtistsIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/settings": typeof SettingsRouteRoute
  "/albums/$albumName": typeof AlbumsAlbumNameRouteRoute
  "/artists/$artist": typeof ArtistsArtistRouteRoute
  "/playlist/$playlistId": typeof PlaylistPlaylistIdRouteRoute
  "/playlist/all": typeof PlaylistAllRouteRoute
  "/tracks/all": typeof TracksAllRouteRoute
  "/albums": typeof AlbumsIndexRoute
  "/artists": typeof ArtistsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/settings": typeof SettingsRouteRoute
  "/albums/$albumName": typeof AlbumsAlbumNameRouteRoute
  "/artists/$artist": typeof ArtistsArtistRouteRoute
  "/playlist/$playlistId": typeof PlaylistPlaylistIdRouteRoute
  "/playlist/all": typeof PlaylistAllRouteRoute
  "/tracks/all": typeof TracksAllRouteRoute
  "/albums/": typeof AlbumsIndexRoute
  "/artists/": typeof ArtistsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/settings"
    | "/albums/$albumName"
    | "/artists/$artist"
    | "/playlist/$playlistId"
    | "/playlist/all"
    | "/tracks/all"
    | "/albums"
    | "/artists"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/settings"
    | "/albums/$albumName"
    | "/artists/$artist"
    | "/playlist/$playlistId"
    | "/playlist/all"
    | "/tracks/all"
    | "/albums"
    | "/artists"
  id:
    | "__root__"
    | "/"
    | "/settings"
    | "/albums/$albumName"
    | "/artists/$artist"
    | "/playlist/$playlistId"
    | "/playlist/all"
    | "/tracks/all"
    | "/albums/"
    | "/artists/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRouteRoute: typeof SettingsRouteRoute
  AlbumsAlbumNameRouteRoute: typeof AlbumsAlbumNameRouteRoute
  ArtistsArtistRouteRoute: typeof ArtistsArtistRouteRoute
  PlaylistPlaylistIdRouteRoute: typeof PlaylistPlaylistIdRouteRoute
  PlaylistAllRouteRoute: typeof PlaylistAllRouteRoute
  TracksAllRouteRoute: typeof TracksAllRouteRoute
  AlbumsIndexRoute: typeof AlbumsIndexRoute
  ArtistsIndexRoute: typeof ArtistsIndexRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/settings": {
      id: "/settings"
      path: "/settings"
      fullPath: "/settings"
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/artists/": {
      id: "/artists/"
      path: "/artists"
      fullPath: "/artists"
      preLoaderRoute: typeof ArtistsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/albums/": {
      id: "/albums/"
      path: "/albums"
      fullPath: "/albums"
      preLoaderRoute: typeof AlbumsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/tracks/all": {
      id: "/tracks/all"
      path: "/tracks/all"
      fullPath: "/tracks/all"
      preLoaderRoute: typeof TracksAllRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/playlist/all": {
      id: "/playlist/all"
      path: "/playlist/all"
      fullPath: "/playlist/all"
      preLoaderRoute: typeof PlaylistAllRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/playlist/$playlistId": {
      id: "/playlist/$playlistId"
      path: "/playlist/$playlistId"
      fullPath: "/playlist/$playlistId"
      preLoaderRoute: typeof PlaylistPlaylistIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/artists/$artist": {
      id: "/artists/$artist"
      path: "/artists/$artist"
      fullPath: "/artists/$artist"
      preLoaderRoute: typeof ArtistsArtistRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/albums/$albumName": {
      id: "/albums/$albumName"
      path: "/albums/$albumName"
      fullPath: "/albums/$albumName"
      preLoaderRoute: typeof AlbumsAlbumNameRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRouteRoute: SettingsRouteRoute,
  AlbumsAlbumNameRouteRoute: AlbumsAlbumNameRouteRoute,
  ArtistsArtistRouteRoute: ArtistsArtistRouteRoute,
  PlaylistPlaylistIdRouteRoute: PlaylistPlaylistIdRouteRoute,
  PlaylistAllRouteRoute: PlaylistAllRouteRoute,
  TracksAllRouteRoute: TracksAllRouteRoute,
  AlbumsIndexRoute: AlbumsIndexRoute,
  ArtistsIndexRoute: ArtistsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
